<section>
    <h1>An error occurred</h1>
    <p><?php echo $this->message ?></p>

    <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
        <p><?php echo get_class($this->exception); ?></p>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?php echo $this->exception->getFile(); ?>:<?php echo $this->exception->getLine(); ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?php echo $this->exception->getMessage(); ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?php echo $this->exception->getTraceAsString(); ?></pre>
            </dd>
        </dl>

        <?php
        $e = $this->exception->getPrevious();
        if ($e):
        ?>
            <section>
                <h1>Previous exceptions</h1>
                <ul>
                    <?php while ($e): ?>
                        <li>
                            <h3><?php echo get_class($e); ?></h3>
                            <dl>
                                <dt>File:</dt>
                                <dd>
                                    <pre><?php echo $e->getFile(); ?>:<?php echo $e->getLine(); ?></pre>
                                </dd>
                                <dt>Message:</dt>
                                <dd>
                                    <pre><?php echo $e->getMessage(); ?></pre>
                                </dd>
                                <dt>Stack trace:</dt>
                                <dd>
                                    <pre><?php echo $e->getTraceAsString(); ?></pre>
                                </dd>
                            </dl>
                        </li>
                    <?php
                    $e = $e->getPrevious();
                    endwhile;
                    ?>
                </ul>
            </section>
        <?php endif; ?>
    <?php endif; ?>
</section>